language: python
python:
  - "3.6"
# dependencies
install:
  - pip install -U flake8
  - pip install -U isort
  - pip install -U yapf
  - pip install -r requirements.txt

script:
  - find . -not -path '*/.eggs/*' -not -path './venv/*' -name '*.py' | xargs flake8
  - python manage.py test
