addons:
  code_climate:
    repo_token: a0d7224eb7113b8d05ea67536a6bdbb53510250b41cbf549366a9131b4b0b27e

language: python
python:
  - "3.6"
# dependencies
install:
  - pip install -U flake8
  - pip install -U isort
  - pip install -U yapf
  - pip install -r requirements.txt

script:
  - find . -not -path '*/.eggs/*' -not -path './env/*' -name '*.py' | xargs flake8 --ignore E501
  - python manage.py test